### ISSUE TITLE
Can RTE be run alongside with another AVCaptureSession? 

### ISSUE THREAD

**Issue by arditnurcaj** [SwiftyTesseract/SwiftyTesseractRTE#7]

**Comment by Steven0351** [comment]
Yes you can. You need to create a concrete type that implements [AVManager](https://swiftytesseract.github.io/SwiftyTesseractRTE/Protocols/AVManager.html#/s:18SwiftyTesseractRTE9AVManagerP8delegateSo44AVCaptureVideoDataOutputSampleBufferDelegate_pSgvp) and share the capture session with whatever else needs it.

**Comment by arditnurcaj** [comment]
Thank you for your response, I'll give it a try.
