### ISSUE TITLE
Variable 'pixImage' passed by reference before being initialized

### ISSUE THREAD

**Issue by peterpaulis** [SwiftyTesseract/SwiftyTesseractRTE#8]
Needs to be moved after the `do`
<img width="1118" alt="Screenshot 2019-08-26 at 11 13 16" src="https://user-images.githubusercontent.com/1956972/63679868-a671ce00-c7f2-11e9-91c1-9b1ac25d0036.png">

**Comment by Steven0351** [comment]
For some reason cocoapods doesn’t respect the Swift version, if you switch the SwiftyTesseract and SwiftyTesseractRTE targets to 4.2 mode it will compile

**Comment by Steven0351** [comment]
This was ultimately addressed in https://github.com/SwiftyTesseract/SwiftyTesseract/pull/53

**Comment by qrobin** [comment]
`var pixImage: Pix = nil` helped me
